apiVersion: v1
kind: Service
metadata:
  name: xxx-CONTAINERNAME-xxx
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: xxx-CONTAINERNAME-xxx
  type: ClusterIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: xxx-CONTAINERNAME-xxx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xxx-CONTAINERNAME-xxx
  template:
    metadata:
      labels:
        app: xxx-CONTAINERNAME-xxx
    spec:
      containers:
      - name: xxx-CONTAINERNAME-xxx
        image: xxx-replace-me-ACRLOGINSERVER-xxx/xxx-CONTAINERNAME-xxx:latest
        ports:
        - containerPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: xxx-CONTAINERNAME-xxx-ingress
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: xxx-CONTAINERNAME-xxx.xxx-replace-me-DNSZONE-xxx
    http:
      paths:
      - backend:
          serviceName: xxx-CONTAINERNAME-xxx
          servicePort: 8080
        path: /
